# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 15:48
from __future__ import unicode_literals

import api.apiconsumer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('token', models.CharField(default=api.apiconsumer.models.generate_user_key, max_length=200, unique=True)),
            ],
        ),
    ]
