# Generated by Django 2.1.2 on 2018-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconsumer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
