# Generated by Django 3.0.3 on 2020-02-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0004_delete_apiuser'),
        ('apiconsumer', '0002_apiconsumer_is_active'),
    ]

    operations = [
    ]
