PRETTIFY_REVIEWBITS = {
  u"rInstructorQuality": "Instructor Quality",
  u"rCourseQuality": "Course Quality",
  u"rDifficulty": "Difficulty",
  u"rCommAbility": "Instructor's Communication",
  u"rInstructorAccess": "Access to Instructor",
  u"rReadingsValue": "Value of Readings",
  u"rAmountLearned": "Amount Learned",
  u"rWorkRequired": "Amount of Work",
  u"rRecommendMajor": "Recommend for Majors",
  u"rRecommendNonMajor": "Recommend for Non-Majors",
  u"rStimulateInterest": "Ability to Stimulate Interest",
  u"rArticulateGoals": "Ability to Articulate Goals",
  u"rSkillEmphasis": "Skill Emphasis",
  u"rHomeworkValuable": "Homework Valuable",
  u"rExamsConsistent": "Exams Consistent",
  u"rAbilitiesChallenged": "Abilities Challenged",
  u"rClassPace": "Class Pace",
  u"rOralSkills": "Oral Skills",
  u"rInstructorConcern": "Instructor Concern",
  u"rInstructorRapport": "Instructor Rapport",
  u"rInstructorAttitude": "Instructor Attitude",
  u"rInstructorEffective": "Instructor Effectiveness",
  u"rGradeFairness": "Grade Fairness",
  u"rNativeAbility": "Native Ability",
  u"rTAQuality": "TA Quality"
}
