# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0002_apiuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='token_last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
